### ISSUE TITLE
Only show PHP errors 

### ISSUE THREAD

**Issue by simplenotezy** [SublimeLinter/SublimeLinter-phplint#21]
How can I remove the red marks from line 9 to 11? I only want to see syntax errors. Not indent stuff.

![image](https://cloud.githubusercontent.com/assets/3786627/16339283/1113a3d0-3a22-11e6-8d51-b88ea2bd41e5.png)

**Comment by ajmichels** [comment]
In the screenshot that you provided it looks like your cursor is on line 8 so we are seeing the linter violation associated with that line, unfortunately you haven't mentioned what the errors are that are occurring on line 9 and 11. If you are able to provide that information I can help you further. Also, are you only running the 'phplint' linter, or do you have others enabled? There are a couple that get enabled by default I believe.

**Comment by simplenotezy** [comment]
Actually this is a screenshot that I copied from another post. 

Issue is I had a file with no errors and I still got those red marked lines around it. How come?

Which plugins can I disable so I only get the small red dot in the left side?

**Comment by ajmichels** [comment]
I get the sense that you are unfamiliar with how SublimeLinter works in general. The red dots indicate when there is an error starting on a particular line. The red highlights (the line around text) is intended to show what specific text is causing a problem. Since SublimeLinter is a framework which tries to support many different linter (including `php -l` via SublimeLinter-phplint) sometimes these lines can be placed a little strangely. Every linter out there returns data in slightly different ways depending on the language being linted.

I recommend taking a look at the SublimeLinter documentation at http://www.sublimelinter.com/

Otherwise you haven't really given me much information to go on. A screen shot of what you are actually seeing would be helpful. As well as the output from `SublimeLinter > Show All Errors` in the context menu (right click in the file). And what would be really helpful would be debugging information (http://www.sublimelinter.com/en/latest/troubleshooting.html#debug-mode).
