### ISSUE TITLE
Showing an error on every closing ")"

### ISSUE THREAD

**Issue by herrmartell** [SublimeLinter/SublimeLinter-phplint#23]
As the title says, it's showing that there is an error on every closing `)`. Also, something inside `header("Location` is giving error as well.

Here's a screenshot:

![](http://i.imgur.com/vRW5Ii7.png)

**Comment by ajmichels** [comment]
If you place your cursor over the highlighted issue it should tell you down in the status bar what the issue is that it is complaining about.

**Comment by herrmartell** [comment]
It does. And it tells the same issue on everything: "unresolved function session_start/session_destroy/header".

Which makes no sense since these are common PHP functions, and I'm using them with no problem at all.

**Comment by ajmichels** [comment]
When I run this exact code through the linter itself I am seeing the same errors. So as much as I hate to say it you are going to have to head over to the [PHPLinter project](http://www.icosaedro.it/phplint/) itself and ask them what the issue is. Maybe start by reading the [documentation](http://www.icosaedro.it/phplint/phplint2/doc/reference.htm). I am personally not very familiar with the linter itself, I am just helping out with the SublimeLinter implementation project which is a very simple script.

To try yourself run `phpl --php-version 5 --print-path relative --print-column-number --tab-size 4 --no-overall [yourfilepath]`. This is almost the exact command that SublimeLinter-phplint is running. The only difference is that we use STDIN instead of passing a file path.

Alternatively you could try using PHP's built in linter (`php -l` via SublimeLinter-php) or my preference is PHP Code Sniffer (`phpcs` via SublimeLinter-phpcs). Either one I think is more active and has more contributors. Neither one has issues with your code snippet.

**Comment by herrmartell** [comment]
Seems like php -l is working. Couldn't make phpcs work. Thanks.

**Comment by ajmichels** [comment]
Keep in mind phpcs will return nothing if there are no errors. So unless you are getting some sort of error message it might be working. I did get a error from phpcs about no doc comment in your code.
