### ISSUE TITLE
Make use of NodeLinter to look for phplint in node_modules

### ISSUE THREAD

**Issue by cjquinn** [SublimeLinter/SublimeLinter-phplint#26]
A couple other node linters use `NodeLinter` to look for their respective executable in `node_modules` it would be cool if this did too! The main reason for this is so that someone pulling down a given project will have all the resources they require to run any pre-commit tasks.

A couple of examples:
* [eslint](https://github.com/roadhump/SublimeLinter-eslint/blob/master/linter.py)
* [sass-lint](https://github.com/skovhus/SublimeLinter-contrib-sass-lint/blob/master/linter.py)

Thoughts? Happy to put in a pull request for this.

**Comment by ajmichels** [comment]
@cjquinn thanks for your feedback. I think we may have run into issues with this before. The NPM package I believe you are referring to (https://www.npmjs.com/package/phplint), created by Wayne Ashley Berry, is actually a different linter than the one that this repository is written for. This repository is targeted at PHPLint (http://www.icosaedro.it/phplint/index.html) created by Umberto Salsi. Salsi's linter is actually written in PHP itself and is executed via the `phpl` command.

It is unfortunate that Berry chose to use the same name but such things happen all of the time in the open source world. For what it's worth Salsi's linter was first published in 2005 while Berry's linter was first published in 2014.

Therefore I don't really think your suggestion makes sense for this project. Feel free to start a separate SublimeLinter project for the linter you are using, though the naming may get confusing.

If I have misunderstood please let me know.

**Comment by cjquinn** [comment]
@ajmichels its seems I jumped the gun and didn't look deeper than the names of the packages! I don't actually use either but was looking for a similar linting solution to eslint and sass-lint which lead me to this. Out of curiosity why would you use phplint over `php -l`?

**Comment by ajmichels** [comment]
The linter within PHP itself (`php -l`) is just a syntax checker which is useful in catching such issues before your code is run. Similar to the kind of checking you get in Java when you compile the code. Since PHP is not compiled there is no such step by default.

Something like [PHPLint](http://www.icosaedro.it/phplint/index.html) goes beyond simple syntax checking. From the website _"PHPLint accurately parses the target PHP source file for strict compliance to its own safety model that goes far beyond a simple syntax validation: flow analysis, tracking of exceptions and errors propagation, consistent type handling, function and method signature check, class autoloading, error mapping into exception, and much more."_ I personally don't use it, but I am sure some people file it useful. 

Other "linters" such as [PHPCS](https://github.com/squizlabs/php_codesniffer) (PHP Code Sniffer) allow you to apply certain rules to the style of your code. For example you might want to ensure that your code following style guidelines such as those defined by the [Zend Framework](https://framework.zend.com/manual/1.11/en/coding-standard.coding-style.html) project or the PHP Framework Interoperability Group's [PSR-1](http://www.php-fig.org/psr/psr-1/) and [PSR-2](http://www.php-fig.org/psr/psr-2/). Such measures can help ensure that your code is easier to read and understand by other developers.

As far as the NPM package "phplint", it appears that all it does is wrap the `php -l` into a node interface. I suppose that is useful for some people in that it allows them to build PHP syntax checking into a Grunt or Gulp task for build automation. That being said it doesn't seem to be a very popular project. It only has 25 stars on GitHub and hasn't been updated in over 10 months. Where as something like PHPCS has almost 3,000 stars and was updated just 13 days ago.

**Comment by cjquinn** [comment]
Ace, thanks for the info!
