### ISSUE TITLE
Tag new release

### ISSUE THREAD

**Issue by james2doyle** [SublimeLinter/SublimeLinter-phplint#36]
Thanks for the plugin. Looks like there are a bunch of commits but no release has been tagged for those new ones? could you please create a new release so package control picks it up?

**Comment by cixtor** [comment]
Here’s the list of all the commits since the last tag:

- ❌ [`cc12752`](https://github.com/SublimeLinter/SublimeLinter-phplint/commit/cc12752) 2016-05-17 Copyright bump
- ❌ [`24a1000`](https://github.com/SublimeLinter/SublimeLinter-phplint/commit/24a1000) 2016-05-17 Update to pydocstyle
- ❌ [`b4e1577`](https://github.com/SublimeLinter/SublimeLinter-phplint/commit/b4e1577) 2017-12-29 pre-spring cleaning
- ✅ [`7c10710`](https://github.com/SublimeLinter/SublimeLinter-phplint/commit/7c10710) 2018-03-25 cleanup deprecated stuff and simplify travis test
- ✅ [`7464568`](https://github.com/SublimeLinter/SublimeLinter-phplint/commit/7464568) 2018-04-02 ok, so phpl also lints php in .html files
- ✅ [`f56e4f7`](https://github.com/SublimeLinter/SublimeLinter-phplint/commit/f56e4f7) 2018-04-02 php5 is already default, expose setting via args
- ✅ [`7664f85`](https://github.com/SublimeLinter/SublimeLinter-phplint/commit/7664f85) 2018-04-02 hardcoding tabsize makes no sense, and doesn't seem to do anything
- ✅ [`1206fc9`](https://github.com/SublimeLinter/SublimeLinter-phplint/commit/1206fc9) 2018-04-02 fix #18, #30 always run on real files
- ❌ [`3653880`](https://github.com/SublimeLinter/SublimeLinter-phplint/commit/3653880) 2018-04-02 update urls
- ❌ [`f4691aa`](https://github.com/SublimeLinter/SublimeLinter-phplint/commit/f4691aa) 2018-04-02 update readme
- ✅ [`c96deb7`](https://github.com/SublimeLinter/SublimeLinter-phplint/commit/c96deb7) 2018-04-02 append ${file} to cmd
- ❌ [`66fd6c9`](https://github.com/SublimeLinter/SublimeLinter-phplint/commit/66fd6c9) 2018-05-11 Updating the command.
- ❌ [`bbd4d19`](https://github.com/SublimeLinter/SublimeLinter-phplint/commit/bbd4d19) 2018-05-26 add config for no-response bot

Marked with a checkmark are the only relevant changes, red cross indicates irrelevant changes.

**Comment by james2doyle** [comment]
Ok cool. But package control is still outdated and so none of the changes (relevant or not) are "deployed"

**Comment by braver** [comment]
Huh, we never tagged anything? Weird.
